TOPDIR ?= ../..
include $(TOPDIR)/.config

$(RMF_SUPPORT)_SRC += protocols/rmf/rmf.c
$(RMF_SUPPORT)_ECMD_SRC += protocols/rmf/rmf_ecmd.c

##############################################################################
# generic fluff
include $(TOPDIR)/scripts/rules.mk
