TOPDIR ?= ../..
include $(TOPDIR)/.config

$(WS2801_SUPPORT)_SRC += services/ws2801/ws2801.c
$(WS2801_SUPPORT)_ECMD_SRC += services/ws2801/ws2801_ecmd.c

#########################################
# generic fluff
include $(TOPDIR)/scripts/rules.mk
