TOPDIR ?= ../..
include $(TOPDIR)/.config

$(MQ135_SUPPORT)_SRC += protocols/mq2/mq2.c
$(MQ135_SUPPORT)_ECMD_SRC += protocols/mq2/mq2_ecmd.c

##############################################################################
# generic fluff
include $(TOPDIR)/scripts/rules.mk
