TOPDIR ?= ../..
include $(TOPDIR)/.config

$(VAILLANT_SUPPORT)_SRC += protocols/vaillant/vaillant.c
$(VAILLANT_SUPPORT)_ECMD_SRC += protocols/vaillant/vaillant_ecmd.c

##############################################################################
# generic fluff
include $(TOPDIR)/scripts/rules.mk
